# Pandas Dataframe

Pandas dataframe is two dimensional lebedled data structure with heterogenously typed columns, both rows and columns have indicies.


<i>pd.DataFrame(data=None, index=None, columns=None, dtype=None)</i>


- Where,
  - <b>data</b>: It can be a 2-D NumPy Array, a Dictionary of Python Lists, or a Dictionary of Panda Series (You can also create a dataframe from a file in CSV, Excel, JSON, HTML format or may be from a database table as well).
  - <b>index:</b> These are the row indices. Will default to RangeIndex (0, 1, 2, ..., n), if index argument is not passed and no indexing information is part of input data.
  - <b>columns:</b> These are the column indices or labels. Will default to RangeIndex (0, 1, 2, ..., n), if index argument is not passed and no indexing information is part of input data.
  - <b>dtype:</b> Data type to force. Only a single dtype is allowed. If None, infer.

In [6]:
import pandas as pd
import numpy as np

In [2]:
df=pd.DataFrame()

In [3]:
df

Empty DataFrame
Columns: []
Index: []

In [4]:
print(df)

Empty DataFrame
Columns: []
Index: []


## Creating a Dataframe from a 2-D NumPy Array


In [7]:
arr = np.random.randint(10,100, size= (6,5))
print("Numpy Array:\n",arr)

df = pd.DataFrame(data=arr)
print("Pandas Dataframe:\n",df)

Numpy Array:
 [[49 25 15 55 95]
 [36 60 82 73 63]
 [86 49 28 84 56]
 [50 70 15 42 56]
 [14 40 58 96 24]
 [46 83 33 47 23]]
Pandas Dataframe:
     0   1   2   3   4
0  49  25  15  55  95
1  36  60  82  73  63
2  86  49  28  84  56
3  50  70  15  42  56
4  14  40  58  96  24
5  46  83  33  47  23


In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       6 non-null      int64
 1   1       6 non-null      int64
 2   2       6 non-null      int64
 3   3       6 non-null      int64
 4   4       6 non-null      int64
dtypes: int64(5)
memory usage: 368.0 bytes


In [9]:
df.columns

RangeIndex(start=0, stop=5, step=1)

In [10]:
df.index

RangeIndex(start=0, stop=6, step=1)

In [11]:
df.ndim

2

In [58]:
df.axes

[Index(['a', 'b', 'c', 'd', 'x', 'y'], dtype='object'),
 Index(['name', 'age', 'addr'], dtype='object')]

In [59]:
df.columns

Index(['name', 'age', 'addr'], dtype='object')

In [62]:
df.dtypes

name     object
age     float64
addr     object
dtype: object

In [13]:
df.size

30

In [63]:
df.count()

name    4
age     3
addr    3
dtype: int64

In [61]:
df.empty

False

In [65]:
df.shape

(6, 3)

In [60]:
df.values

array([['Arif', 50.0, 'Lahore'],
       ['Hadeed', nan, nan],
       ['Mujahid', nan, nan],
       ['Maaz', 18.0, ''],
       [nan, 22.0, 'Karachi'],
       [nan, nan, nan]], dtype=object)

In [22]:
col_name=['age','num1','num2','num3','num4']
df=pd.DataFrame(data=arr,columns=col_name)
df

age  num1  num2  num3  num4
0   49    25    15    55    95
1   36    60    82    73    63
2   86    49    28    84    56
3   50    70    15    42    56
4   14    40    58    96    24
5   46    83    33    47    23

In [23]:
df = pd.DataFrame(data=arr,index=['hello','age','num1','num4','size','row'])
df

0   1   2   3   4
hello  49  25  15  55  95
age    36  60  82  73  63
num1   86  49  28  84  56
num4   50  70  15  42  56
size   14  40  58  96  24
row    46  83  33  47  23

In [28]:
s = df[1]
s

hello    25
age      60
num1     49
num4     70
size     40
row      83
Name: 1, dtype: int64

In [31]:
s.dtype

dtype('int64')

Create a NumPy array containing the heights and weights of a group of people. Each row should represent a single person, with the first column containing the person's height (in inches) and the second column containing their weight (in pounds). Use this array to create a Pandas DataFrame.

In [39]:
arr = np.array([[57,62],
               [12,45],
               [45,69],
               [55,78]])
col_name=['height','weight']
df = pd.DataFrame(data=arr,columns=col_name)
df

height  weight
0      57      62
1      12      45
2      45      69
3      55      78

Create a NumPy array containing the sales figures for a company's products. Each row should represent a single product, with the first column containing the product name and the second column containing the sales figure (in dollars). Use this array to create a Pandas DataFrame.

In [40]:
sales_data = np.array([
    ["Product A", 1000],
    ["Product B", 2000],
    ["Product C", 1500],
    ["Product D", 3000],
    ["Product E", 2500]
])

df = pd.DataFrame(data=sales_data)
df

0     1
0  Product A  1000
1  Product B  2000
2  Product C  1500
3  Product D  3000
4  Product E  2500

## Creating a Dataframe from a Dictionary of Python Lists

- You can create a dataframe object from a dictionary of Python Lists
  - The dictionary Keys become the column names, and
  - The dictionary Values are lists/arrays containing data for the respective columns.

In [41]:
arr = {
    'name':['Azib','Taha','Sohaib','Umar','Sarmad','Shazif','Hayyan'],
    'age':[12,16,22,21,23,27,2],
    'address':['Lahore','Karachi','Lahore','Murree','Murree','Lahore','Karachi']
    
}

df = pd.DataFrame(data=arr)
df

name  age  address
0    Azib   12   Lahore
1    Taha   16  Karachi
2  Sohaib   22   Lahore
3    Umar   21   Murree
4  Sarmad   23   Murree
5  Shazif   27   Lahore
6  Hayyan    2  Karachi

In [43]:
row_labels = ['MS01', 'MS02', 'MS03', 'MS04', 'MS05', 'MS06','MS07']
df.index = row_labels
df

name  age  address
MS01    Azib   12   Lahore
MS02    Taha   16  Karachi
MS03  Sohaib   22   Lahore
MS04    Umar   21   Murree
MS05  Sarmad   23   Murree
MS06  Shazif   27   Lahore
MS07  Hayyan    2  Karachi

## Creating a Dataframe from Dictionary of Panda Series


In [45]:
dic = {
    'name':pd.Series(data=['Azib','Sarmad','Hanzala','Taha'],index=['a','b','c','d']),
    'age':pd.Series(data=[19,23,20,2],index=['a','b','c','d'])
}
df = pd.DataFrame(data=dic)
df

name  age
a     Azib   19
b   Sarmad   23
c  Hanzala   20
d     Taha    2

In [46]:
dic = {
    'name': pd.Series(data=['Azib','Hala','Taha','Sohaib','Hayyan','Umar'],index=['a','b','c','e','d','i']),
    'age': pd.Series(data=[12,42,23,18,14,24],index=['b','a','i','c','d','e'])
}

df =pd.DataFrame(data=dic)
df

name  age
a    Azib   42
b    Hala   12
c    Taha   18
d  Hayyan   14
e  Sohaib   24
i    Umar   23

In [47]:
dict = {
    "name": pd.Series(data=['Arif', 'Hadeed', 'Mujahid', 'Maaz'], index=['a','b','c', 'd']),
    "age": pd.Series(data=[50, 22,np.nan, 18], index=['a','b','c','d']),
    "addr": pd.Series(data=['Lahore', '', 'Peshawer','Karachi'], index=['a','b','c', 'd']),
}
df = pd.DataFrame(dict)
df

name   age      addr
a     Arif  50.0    Lahore
b   Hadeed  22.0          
c  Mujahid   NaN  Peshawer
d     Maaz  18.0   Karachi

In [48]:
df.head()

name   age      addr
a     Arif  50.0    Lahore
b   Hadeed  22.0          
c  Mujahid   NaN  Peshawer
d     Maaz  18.0   Karachi

In [49]:
df.head(-4)

Empty DataFrame
Columns: [name, age, addr]
Index: []

In [50]:
dict = {
    "name": pd.Series(['Arif', 'Hadeed', 'Mujahid', 'Maaz'], index=['a','b','c', 'd']),
    "age": pd.Series([50, 22,np.nan, 18], index=['a','x','y','d']),
    "addr": pd.Series(['Lahore', '','Karachi'], index=['a', 'd', 'x']),
}
df = pd.DataFrame(dict)
df

name   age     addr
a     Arif  50.0   Lahore
b   Hadeed   NaN      NaN
c  Mujahid   NaN      NaN
d     Maaz  18.0         
x      NaN  22.0  Karachi
y      NaN   NaN      NaN

In [51]:
df.head()

name   age     addr
a     Arif  50.0   Lahore
b   Hadeed   NaN      NaN
c  Mujahid   NaN      NaN
d     Maaz  18.0         
x      NaN  22.0  Karachi

In [52]:
df.head(-4)

name   age    addr
a    Arif  50.0  Lahore
b  Hadeed   NaN     NaN

In [53]:
df.tail(-4)

name   age     addr
x  NaN  22.0  Karachi
y  NaN   NaN      NaN

In [54]:
df.tail()

name   age     addr
b   Hadeed   NaN      NaN
c  Mujahid   NaN      NaN
d     Maaz  18.0         
x      NaN  22.0  Karachi
y      NaN   NaN      NaN

In [55]:
df.head(4)

name   age    addr
a     Arif  50.0  Lahore
b   Hadeed   NaN     NaN
c  Mujahid   NaN     NaN
d     Maaz  18.0

In [56]:
df.head(-1)

name   age     addr
a     Arif  50.0   Lahore
b   Hadeed   NaN      NaN
c  Mujahid   NaN      NaN
d     Maaz  18.0         
x      NaN  22.0  Karachi

In [57]:
df.head(-2)

name   age    addr
a     Arif  50.0  Lahore
b   Hadeed   NaN     NaN
c  Mujahid   NaN     NaN
d     Maaz  18.0